import useProcessedPathname from '../hooks/useProcessedPathname';

const INITIAL_COLUMN_WIDTH = 150;

export const useTableData = () => {
  const currentPage = useProcessedPathname();

  function handleInitialColumnWidth(columnIndex) {
    return localStorage.getItem(`p-${currentPage}_c-${columnIndex}_width`)
      ? localStorage.getItem(`p-${currentPage}_c-${columnIndex}_width`)
      : INITIAL_COLUMN_WIDTH;
  }

  function getInitialTableData() {
    const initialTableData = {
      ['users']: {
        columns: [
          {
            title: 'Name',
            key: 'name',
            width: handleInitialColumnWidth(0),
          },
          {
            title: 'Age',
            key: 'age',
            width: handleInitialColumnWidth(1),
          },
          {
            title: 'Address',
            key: 'address',
            width: handleInitialColumnWidth(2),
          },
          {
            title: 'Tags',
            key: 'tags',
            width: handleInitialColumnWidth(3),
          },
          {
            title: 'Total',
            key: 'total',
            width: handleInitialColumnWidth(4),
          },
        ],
        raws: [
          {
            key: '1',
            name: 'John Brown',
            age: 32,
            address: 'New York No. 1 Lake Park',
            tags: ['nice', 'developer'],
            total: 20000,
          },
          {
            key: '2',
            name: 'Jim Green',
            age: 42,
            address: 'London No. 1 Lake Park',
            tags: ['loser'],
            total: 23324,
          },
          {
            key: '3',
            name: 'Joe Black',
            age: 32,
            address: 'Sydney No. 1 Lake Park',
            tags: ['cool', 'teacher'],
            total: 274454,
          },
          {
            key: '4',
            name: 'Anna White',
            age: 25,
            address: 'Berlin No. 2 Riverside',
            tags: ['developer', 'teacher'],
            total: 239836,
          },
          {
            key: '5',
            name: 'Ella Blue',
            age: 29,
            address: 'Paris No. 3 Square',
            tags: ['nice'],
            total: 964763,
          },
          {
            key: '6',
            name: 'James Smith',
            age: 35,
            address: 'Tokyo No. 4 Street',
            tags: ['loser', 'cool'],
            total: 5739356,
          },
          {
            key: '7',
            name: 'Michael Johnson',
            age: 40,
            address: 'Oslo No. 5 Road',
            tags: ['teacher', 'developer'],
            total: 1947643,
          },
          {
            key: '8',
            name: 'Jessica Martin',
            age: 28,
            address: 'Rome No. 6 Avenue',
            tags: ['cool'],
            total: 903744,
          },
          {
            key: '9',
            name: 'Sophia Turner',
            age: 30,
            address: 'Madrid No. 7 Blvd',
            tags: ['nice', 'developer'],
            total: 572307,
          },
          {
            key: '10',
            name: 'Daniel Lee',
            age: 33,
            address: 'Beijing No. 8 Lane',
            tags: ['loser', 'teacher'],
            total: 645384,
          },
          {
            key: '11',
            name: 'Lucas Walker',
            age: 36,
            address: 'Moscow No. 9 Park',
            tags: ['cool', 'nice'],
            total: 392746,
          },
          {
            key: '12',
            name: 'Emily Hall',
            age: 24,
            address: 'Seoul No. 10 Drive',
            tags: ['teacher', 'developer'],
            total: 409246,
          },
          {
            key: '13',
            name: 'David Allen',
            age: 39,
            address: 'Dubai No. 11 Street',
            tags: ['nice', 'cool'],
            total: 7947533,
          },
          {
            key: '14',
            name: 'Oliver Taylor',
            age: 31,
            address: 'São Paulo No. 12 Way',
            tags: ['developer', 'loser'],
            total: 20946224,
          },
          {
            key: '15',
            name: 'Mia Harris',
            age: 27,
            address: 'Cape Town No. 13 Place',
            tags: ['teacher'],
            total: 109374673,
          },
          {
            key: '16',
            name: 'Ethan Evans',
            age: 28,
            address: 'Johannesburg No. 14 Drive',
            tags: ['cool', 'developer'],
            total: 59374362,
          },
          {
            key: '17',
            name: 'Liam King',
            age: 37,
            address: 'Mumbai No. 15 Way',
            tags: ['nice', 'loser'],
            total: 8759383,
          },
          {
            key: '18',
            name: 'Isabella Lewis',
            age: 29,
            address: 'Buenos Aires No. 16 Blvd',
            tags: ['teacher', 'cool'],
            total: 19172763,
          },
          {
            key: '19',
            name: 'Ava Adams',
            age: 24,
            address: 'Toronto No. 17 Road',
            tags: ['developer', 'nice'],
            total: 5809378,
          },
          {
            key: '20',
            name: 'William Thompson',
            age: 31,
            address: 'Mexico City No. 18 Street',
            tags: ['loser', 'teacher'],
            total: 593736,
          },
          {
            key: '21',
            name: 'Benjamin Carter',
            age: 40,
            address: 'Bangkok No. 19 Avenue',
            tags: ['cool', 'developer'],
            total: 2984634,
          },
          {
            key: '22',
            name: 'Charlotte Roberts',
            age: 34,
            address: 'New Delhi No. 20 Blvd',
            tags: ['teacher', 'nice'],
            total: 573037,
          },
          {
            key: '23',
            name: 'Abigail Turner',
            age: 30,
            address: 'Jakarta No. 21 Drive',
            tags: ['loser', 'cool'],
            total: 79038367,
          },
          {
            key: '24',
            name: 'James Clark',
            age: 38,
            address: 'Manila No. 22 Lane',
            tags: ['developer', 'teacher'],
            total: 3929264,
          },
          {
            key: '25',
            name: 'Sophia Stewart',
            age: 35,
            address: 'Istanbul No. 23 Park',
            tags: ['nice', 'cool'],
            total: 69337743,
          },
          {
            key: '26',
            name: 'Oliver Scott',
            age: 29,
            address: 'Lisbon No. 24 Way',
            tags: ['teacher', 'loser'],
            total: 5732037,
          },
          {
            key: '27',
            name: 'Lily Jenkins',
            age: 32,
            address: 'Copenhagen No. 25 Street',
            tags: ['developer', 'cool'],
            total: 5373937,
          },
          {
            key: '28',
            name: 'Noah Palmer',
            age: 40,
            address: 'Zurich No. 26 Blvd',
            tags: ['nice', 'teacher'],
            total: 6902734,
          },
          {
            key: '29',
            name: 'Emma Simmons',
            age: 28,
            address: 'Brussels No. 27 Lane',
            tags: ['cool', 'loser'],
            total: 694863,
          },
          {
            key: '30',
            name: 'Logan Perry',
            age: 36,
            address: 'Stockholm No. 28 Way',
            tags: ['teacher', 'developer'],
            total: 4448762,
          },
          {
            key: '31',
            name: 'Grace Nelson',
            age: 27,
            address: 'Helsinki No. 29 Drive',
            tags: ['nice', 'cool'],
            total: 66873874,
          },
          {
            key: '32',
            name: 'Lucas Murphy',
            age: 33,
            address: 'Osaka No. 30 Park',
            tags: ['loser', 'teacher'],
            total: 698373,
          },
          {
            key: '33',
            name: 'Ella Phillips',
            age: 39,
            address: 'Beirut No. 31 Blvd',
            tags: ['developer', 'nice'],
            total: 683936,
          },
          {
            key: '34',
            name: 'Leo Gonzalez',
            age: 31,
            address: 'Cairo No. 32 Street',
            tags: ['teacher', 'cool'],
            total: 11927364,
          },
          {
            key: '35',
            name: 'Amelia Butler',
            age: 34,
            address: 'Nairobi No. 33 Way',
            tags: ['nice', 'loser'],
            total: 9909283,
          },
          {
            key: '36',
            name: 'Henry Simmons',
            age: 30,
            address: 'Budapest No. 34 Drive',
            tags: ['cool', 'teacher'],
            total: 1010838,
          },
          {
            key: '37',
            name: 'Mia Washington',
            age: 28,
            address: 'Prague No. 35 Park',
            tags: ['developer', 'loser'],
            total: 1028334,
          },
          {
            key: '38',
            name: 'Zoe Harris',
            age: 35,
            address: 'Vienna No. 36 Lane',
            tags: ['teacher', 'nice'],
            total: 599826,
          },
          {
            key: '39',
            name: 'Jack Murphy',
            age: 38,
            address: 'Dublin No. 37 Way',
            tags: ['loser', 'cool'],
            total: 398765,
          },
          {
            key: '40',
            name: 'Chloe Edwards',
            age: 27,
            address: 'Santiago No. 38 Blvd',
            tags: ['nice', 'developer'],
            total: 984636,
          },
          {
            key: '41',
            name: 'Benjamin Mitchell',
            age: 29,
            address: 'Bogota No. 39 Drive',
            tags: ['teacher', 'loser'],
            total: 57937,
          },
          {
            key: '42',
            name: 'Natalie Parker',
            age: 31,
            address: 'Rio de Janeiro No. 40 Park',
            tags: ['cool', 'nice'],
            total: 994973,
          },
          {
            key: '43',
            name: 'Blake Anderson',
            age: 34,
            address: 'Buenos Aires No. 41 Lane',
            tags: ['developer', 'teacher'],
            total: 7893846,
          },
          {
            key: '44',
            name: 'Madison Torres',
            age: 28,
            address: 'Montevideo No. 42 Way',
            tags: ['nice', 'cool'],
            total: 229933,
          },
          {
            key: '45',
            name: 'Aiden Rogers',
            age: 32,
            address: 'Caracas No. 43 Street',
            tags: ['loser', 'developer'],
            total: 553673,
          },
        ],
      },
      ['store']: {
        columns: [
          {
            title: 'Product',
            key: 'product',
            width: handleInitialColumnWidth(0),
          },
          {
            title: 'Quantity',
            key: 'quantity',
            width: handleInitialColumnWidth(1),
          },
          {
            title: 'Brand',
            key: 'brand',
            width: handleInitialColumnWidth(2),
          },
          {
            title: 'Supplier',
            key: 'supplier',
            width: handleInitialColumnWidth(3),
          },
          {
            title: 'Price',
            key: 'price',
            width: handleInitialColumnWidth(4),
          },
        ],
        raws: [
          {
            key: '1',
            product: 'Laptop',
            quantity: 50,
            brand: 'Dell',
            supplier: 'TechCorp',
            price: 1000,
          },
          {
            key: '2',
            product: 'Smartphone',
            quantity: 200,
            brand: 'Samsung',
            supplier: 'MobileWorld',
            price: 800,
          },
          {
            key: '3',
            product: 'Tablet',
            quantity: 80,
            brand: 'Apple',
            supplier: 'TechCorp',
            price: 1200,
          },
          {
            key: '4',
            product: 'Monitor',
            quantity: 60,
            brand: 'LG',
            supplier: 'ScreenMasters',
            price: 300,
          },
          {
            key: '5',
            product: 'Keyboard',
            quantity: 150,
            brand: 'Logitech',
            supplier: 'GadgetGurus',
            price: 50,
          },
          {
            key: '6',
            product: 'Mouse',
            quantity: 140,
            brand: 'HP',
            supplier: 'TechCorp',
            price: 40,
          },
          {
            key: '7',
            product: 'Earphones',
            quantity: 300,
            brand: 'Sony',
            supplier: 'MusicMakers',
            price: 100,
          },
          {
            key: '8',
            product: 'Smartwatch',
            quantity: 120,
            brand: 'Fitbit',
            supplier: 'WristTech',
            price: 220,
          },
          {
            key: '9',
            product: 'Hard Drive',
            quantity: 170,
            brand: 'Western Digital',
            supplier: 'StorageSolutions',
            price: 90,
          },
          {
            key: '10',
            product: 'Printer',
            quantity: 40,
            brand: 'Canon',
            supplier: 'PrintPros',
            price: 180,
          },
          {
            key: '11',
            product: 'Camera',
            quantity: 90,
            brand: 'Nikon',
            supplier: 'PhotoFutures',
            price: 1300,
          },
          {
            key: '12',
            product: 'Laptop',
            quantity: 50,
            brand: 'Dell',
            supplier: 'TechCorp',
            price: 1000,
          },
          {
            key: '13',
            product: 'Smartphone',
            quantity: 200,
            brand: 'Samsung',
            supplier: 'MobileWorld',
            price: 800,
          },
          {
            key: '14',
            product: 'Tablet',
            quantity: 80,
            brand: 'Apple',
            supplier: 'TechCorp',
            price: 1200,
          },
          {
            key: '15',
            product: 'Monitor',
            quantity: 60,
            brand: 'LG',
            supplier: 'ScreenMasters',
            price: 300,
          },
          {
            key: '16',
            product: 'Keyboard',
            quantity: 150,
            brand: 'Logitech',
            supplier: 'GadgetGurus',
            price: 50,
          },
          {
            key: '17',
            product: 'Mouse',
            quantity: 140,
            brand: 'HP',
            supplier: 'TechCorp',
            price: 40,
          },
          {
            key: '18',
            product: 'Earphones',
            quantity: 300,
            brand: 'Sony',
            supplier: 'MusicMakers',
            price: 100,
          },
          {
            key: '19',
            product: 'Smartwatch',
            quantity: 120,
            brand: 'Fitbit',
            supplier: 'WristTech',
            price: 220,
          },
          {
            key: '20',
            product: 'Smartphone',
            quantity: 200,
            brand: 'Samsung',
            supplier: 'MobileWorld',
            price: 800,
          },
          {
            key: '21',
            product: 'Tablet',
            quantity: 80,
            brand: 'Apple',
            supplier: 'TechCorp',
            price: 1200,
          },
        ],
      },
      ['books']: {
        columns: [
          {
            title: 'Title',
            key: 'title',
            width: handleInitialColumnWidth(0),
          },
          {
            title: 'Published Date',
            key: 'date',
            width: handleInitialColumnWidth(1),
          },
          {
            title: 'Author',
            key: 'author',
            width: handleInitialColumnWidth(2),
          },
          {
            title: 'Genre',
            key: 'genres',
            width: handleInitialColumnWidth(3),
          },

          {
            title: 'Revenues',
            key: 'revenues',
            width: handleInitialColumnWidth(4),
          },
        ],
        raws: [
          {
            key: '1',
            title: 'To Kill a Mockingbird',
            date: '1960',
            author: 'Harper Lee',
            genres: ['Historical Fiction'],
            revenues: 9725432,
          },
          {
            key: '2',
            title: '1984',
            date: '1949',
            author: 'George Orwell',
            genres: ['Dystopian'],
            revenues: 14997424,
          },
          {
            key: '3',
            title: 'To Kill a Mockingbird',
            date: '1960',
            author: 'Harper Lee',
            genres: ['Historical Fiction'],
            revenues: 873972,
          },
          {
            key: '4',
            title: '1984',
            date: '1949',
            author: 'George Orwell',
            genres: ['Dystopian'],
            revenues: 4829649,
          },
          {
            key: '5',
            title: 'Moby-Dick',
            date: '1851',
            author: 'Herman Melville',
            genres: ['Adventure', 'Epic'],
            revenues: 5544211,
          },
          {
            key: '6',
            title: 'Brave New World',
            date: '1932',
            author: 'Aldous Huxley',
            genres: ['Dystopian', 'Science Fiction'],
            revenues: 9986655,
          },
          {
            key: '7',
            title: 'Crime and Punishment',
            date: '1866',
            author: 'Fyodor Dostoevsky',
            genres: ['Psychological Fiction'],
            revenues: 2566,
          },
          {
            key: '8',
            title: 'The Catcher in the Rye',
            date: '1951',
            author: 'J.D. Salinger',
            genres: ['Bildungsroman'],
            revenues: 8887544,
          },
          {
            key: '9',
            title: 'The Odyssey',
            date: '1875',
            author: 'Homer',
            genres: ['Epic'],
            revenues: 4788,
          },
          {
            key: '10',
            title: 'War and Peace',
            date: '1869',
            author: 'Leo Tolstoy',
            genres: ['Historical Novel'],
            revenues: 1237894560,
          },
        ],
      },
      ['devices']: {
        columns: [
          {
            title: 'Device',
            key: 'device',
            width: handleInitialColumnWidth(0),
          },
          {
            title: 'Release Date',
            key: 'date',
            width: handleInitialColumnWidth(1),
          },
          {
            title: 'Model',
            key: 'model',
            width: handleInitialColumnWidth(2),
          },
          {
            title: 'Brand',
            key: 'brand',
            width: handleInitialColumnWidth(3),
          },

          {
            title: 'Price',
            key: 'price',
            width: handleInitialColumnWidth(4),
          },
        ],
        raws: [
          {
            key: '1',
            device: 'Smartphone',
            date: '2021',
            model: 'Galaxy S21',
            brand: 'Samsung',
            price: 799,
          },
          {
            key: '2',
            device: 'Laptop',
            date: '2020',
            model: 'MacBook Pro',
            brand: 'Apple',
            price: 1299,
          },
          {
            key: '3',
            device: 'Tablet',
            date: '2021',
            model: 'iPad Pro',
            brand: 'Apple',
            price: 999,
          },
          {
            key: '4',
            device: 'Smartwatch',
            date: '2022',
            model: 'Watch Series 7',
            brand: 'Apple',
            price: 399,
          },
          {
            key: '5',
            device: 'Smartphone',
            date: '2021',
            model: 'Pixel 5a',
            brand: 'Google',
            price: 449,
          },
          {
            key: '6',
            device: 'Laptop',
            date: '2019',
            model: 'Surface Laptop 3',
            brand: 'Microsoft',
            price: 999,
          },
          {
            key: '7',
            device: 'Tablet',
            date: '2021',
            model: 'Galaxy Tab S7+',
            brand: 'Samsung',
            price: 849,
          },
          {
            key: '8',
            device: 'Smartphone',
            date: '2022',
            model: 'OnePlus 9 Pro',
            brand: 'OnePlus',
            price: 969,
          },
          {
            key: '9',
            device: 'Laptop',
            date: '2021',
            model: 'Dell XPS 13',
            brand: 'Dell',
            price: 1249,
          },
          {
            key: '10',
            device: 'Smartwatch',
            date: '2021',
            model: 'Galaxy Watch 4',
            brand: 'Samsung',
            price: 259,
          },
          {
            key: '11',
            device: 'Tablet',
            date: '2020',
            model: 'Fire HD 10',
            brand: 'Amazon',
            price: 149,
          },
          {
            key: '12',
            device: 'Smartphone',
            date: '2019',
            model: 'iPhone 11 Pro',
            brand: 'Apple',
            price: 999,
          },
        ],
      },
    };
    return initialTableData[currentPage] || initialTableData['users'];
  }

  return {
    handleInitialColumnWidth,
    getInitialTableData,
  };
};
